### PR TITLE
Fixes on Info.fromName()

### PR DESCRIPTION
**Pull request by expobrain**
Info.fromName() iterates over `module.paths` instead of looking for a `node_modules` directory relative to the given module

### CODE REVIEW

**Comment by davidkudera** [comment]
Thank you, I'll take a look at it later today.

**Comment by expobrain** [comment]
Just found this PR still open, did you have a chance to look at it?

**Comment by davidkudera** [comment]
Ou.. Sorry sir.. 

Did you try to run tests? I didn't setup travis for this repository..

**Comment by expobrain** [comment]
All of them passing:

  Info
    #constructor()
      ✓ should throw an error if directory does not exists
      ✓ should throw an error if path is not directory
      ✓ should throw an error if package.json does not exists
    #getPackagePath()
      ✓ should return path to package.json file
    #getData()
      ✓ should return json data from package.json file
    #getName()
      ✓ should return name of module
    #getPath()
      ✓ should return path to module directory
    #getMainFile()
      ✓ should return path to main file
      ✓ should return path to main file when it is not defined in package.json
      ✓ should return null when main file is not defined and index.js does not exists
    #getModuleName()
      ✓ should throw an error if file is not placed in module
      ✓ should throw an error if file does not exists
      ✓ should throw an error if path is not file
      ✓ should get name of simple module itself
      ✓ should get name of advanced module itself
      ✓ should get name of main file relatively
      ✓ should get name of main file of advanced module relatively
      ✓ should get name of file in module for require method
      ✓ should get name of file in module for absolute path
    #isNpmDependency()
      ✓ should return true
      ✓ should return false
    #isFileInModule()
      ✓ should return true for non npm module file
      ✓ should return false for file in npm module called from non npm module
      ✓ should return true for file from npm module
      ✓ should return false for file in submodule of npm module

  Info.fromFile
    ✓ should create Info object from main js file
    ✓ should create Info object for advanced module
    #getMainFile()
      ✓ should get main file for advanced module
    #getPath()
      ✓ should return path to module directory

  Info.fromName
    ✓ should create Info object from module name
    ✓ should create Info object for advanced module
    #getMainFile()
      ✓ should get main file for advanced module

  Info.self
    #getMainFile()
      ✓ should get main file for advanced module

  33 passing (82ms)

**Comment by davidkudera** [comment]
:+1: thank you, later today I'll tag new version (probably the last one)

**Comment by expobrain** [comment]
I just read that you are abandoning that project and you're looking for a new maintainer, I can take it over if you like

**Comment by davidkudera** [comment]
That would be really great sir :wink: 

May I ask you to send me an email, so we can discuss this further please?

**Pull request merged**
